---
- name: Deploiement et configuration du service dhcp conteneurise
  hosts: all
  become: true
  gather_facts: true

 # 1) Prérequis communs
  pre_tasks:
    - name: Assurer que snapd est présent
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: true
      when: ansible_pkg_mgr == 'apt'

    - name: Mise à jour de l'index APT
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == 'apt'
      tags: [packages]

  # 2) Deploiement des differents Rôles
  roles:
    - role: lxd-dhcp

